modLoader = "javafml"
loaderVersion = "[44,)"
license = "${license}"
logoBlur = false
issueTrackerURL = "${issue_tracker}"
logoFile = "icon.png"
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
[[dependencies.assortedtech]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.assortedtech]]
modId = "minecraft"
mandatory = true
versionRange = "${forge_mc_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.assortedtech]]
modId = "assortedlib"
mandatory = true
versionRange = "[1.0.1,)"
ordering = "NONE"
side = "BOTH"
