# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml"
loaderVersion="[39,)"
license="GPL-3.0 License"
issueTrackerURL="https://github.com/grim3212/AssortedTech"

[[mods]] #mandatory
modId="assortedtech"
version="${file.jarVersion}"
displayName="Assorted Tech"
#updateJSONURL=""
displayURL="https://assortedmods.com/tech"
logoFile="logo.png"
authors="Grim3212"
description='''
Contains an assorted group of additions based around technology, machines, and logic.
'''

[[dependencies.assortedtech]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.assortedtech]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"
